# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

#title: BOOK OF PRIMES
title: PROD
author: PROD GANG
logo: imgs/logo.svg

execute:
  execute_notebooks: auto

launch_buttons:
  thebe: true


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/prodgang/prod  # Online location of your book
  #path_to_book: words  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: false
  extra_footer: "<p> © Copyright I sure hope you do </p>"
  extra_css: ["_static/custom.css"]
  #extra_javascript: 
  #  - _static/giscus.js


sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_show_copyright: false

  extra_extensions:
    - sphinx_proof

myst:
  jupytext:
    formats: ipynb,md


parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - strikethrough
